[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 20

[[main]]
  name = "Resume"
  pageRef = "/resume"
  weight = 30

[[main]]
  name = "Poland Life"
  pageRef = "/posts/poland-life"
  weight = 40

[[main]]
  name = "DevOps"
  pageRef = "/posts/devops"
  weight = 50

[[main]]
  name = "Contact"
  pageRef = "/contact"
  weight = 60
