[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 20

[[main]]
  name = "Resume"
  pageRef = "/resume"
  weight = 30

[[main]]
  name = "Tech Logs"
  pageRef = "/posts/tech-logs"
  weight = 50

[[main]]
  name = "Contact"
  pageRef = "/contact"
  weight = 60
